phraseapp:
  access_token: abe25dfa03ef227ef182258e93760a8f706b8c02aaec2cee3f84effe38133439
  project_id: 340af67ea80540d3ccb5deeaf984d8b9
  push:
    sources:
      - file: ./<locale_name>.json
        params:
          file_format: react_simple_json
  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: react_simple_json
